### ISSUE TITLE
`unix-dgram` optionality problem using specific Node.js Docker image

### ISSUE THREAD

**Issue by pintarj** [meetecho/janode#16]
When using Janode in Docker containers I've faced the same problem as in issue #10:
```
node:internal/errors:477
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'unix-dgram' imported from /app/node_modules/janode/src/transport-unix.js
    at new NodeError (node:internal/errors:387:5)
    at packageResolve (node:internal/modules/esm/resolve:951:9)
    at moduleResolve (node:internal/modules/esm/resolve:1000:20)
    at defaultResolve (node:internal/modules/esm/resolve:1214:11)
    at nextResolve (node:internal/modules/esm/loader:165:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:844:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:431:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```
The issue occurs when the Docker image is built from the base image `node:16-slim`. Meanwhile it works well and as expected when using the `node:16` image.

## Steps to reproduce

1) `npm init` with default values
2) `npm insall janode`
3) add the `"type": "module"` line to the `package.json`

The `package.json` file should look like this:

```js
{
  "name": "janode-issue",
  "version": "1.0.0",
  "description": "",
  "type": "module", // added line
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "janode": "^1.6.4"
  }
}
```
3) Create the `main.js` file with the following content:
```js
import Janode from 'janode'
```
4) Create the `Dockerfile` file with the following content:
```dockerfile
FROM node:16-slim
WORKDIR /app/
COPY main.js ./
COPY package*.json ./
RUN npm install
CMD ["node", "main.js"]
```
5) Build the Docker image:
```console
docker build --tag xyz .
```
6) Run the built Docker image:
```console
docker run --rm xyz
```
7) Error should be occured.

## Appendix

The zip with all the mentioned files (plus `package-lock.json` file): [janode-issue.zip](https://github.com/meetecho/janode/files/9741574/janode-issue.zip)

**Comment by pintarj** [comment]
But I’m not installing/building `unix-dgram` at all. Isn’t there a way that `janode` check the presence of the optional package (can dynamic import do that?).

**Comment by atoppi** [comment]
`npm` is installing (at least it is trying to install) every janode dependency for you.

Currently there is no check for the optional package.
Dynamic import should work (e.g. loading the module when a unix transport is being requested) but I'd prefer trying other strategies before considering it, since dynamic importing does not cope well with tools like bundlers, static analyzers and so on.

For example, when bundling in browsers, we replace `transport-unix.js` with a stub module.
If you got any suggestion about the best strategy to adopt here, please feel free to share your ideas.

**Comment by atoppi** [comment]
I guess since we switched to es modules and every dep is now being statically imported asap, making unix-dgram an optional dependency in package.json does not make any sense. Skipping that dep with ``--omit=optional` will just trigger a failure when starting janode and it will be also be a kind of "silent" failure.
 
I'll move `unix-dgram` to the standard deps in order to have an error message when installing janode and avoid silent failures like you experienced.

**Comment by atoppi** [comment]
done in https://github.com/meetecho/janode/commit/ee0d97b10f4c9421a58f1fbb11bf0e117a1718b1

**Comment by pintarj** [comment]
Thanks for the patch, at least now it doesn't silently fail anymore. But forces Docker images to have some tools (python, make, g++, ...) installed, adding hundreds of MB, just to install an "optional" dependency that one doesn't uses. It's not a critic, just a recap.

I'll try to think about a solution that doesn't includes the _dynamic import_.

**Comment by atoppi** [comment]
closing for now, I'm still open to suggestions for optional dependencies
