### ISSUE TITLE
support of recordplay plugin.

### ISSUE THREAD

**Issue by azhar-codeprism** [meetecho/janode#19]
Hi,
Can we know if janode will ever support the recordplay plugin? If there is already a solution can you point me in the right direction?

**Comment by atoppi** [comment]
Not in the short term unfortunately since it is not among the most deployed plugins.
If other people show interest in this feature I could reconsider the idea but honestly I'm more focused on improving other aspects.

For other implementations take a look here
https://janus.conf.meetecho.com/docs/resources.html
